name: CI
on: 
  workflow_dispatch:
 
jobs:
 node-server-build:
    runs-on: windows-latest
    timeout-minutes: 360
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
        name: Server build 
      - name: Run the Server build process
        uses: addnab/docker-run-action@v3
        with:
            image: ubuntu:24.04
            run: |
                lscpu
